#property strict
#property version   "1.00"
#property description "Strategy EA: Buy Gold near 100, sell/close near 140, with fixed SL/TP and date-filtered trading window."
#property copyright "Generated by ChatGPT"

#include <Trade/Trade.mqh>

input double InpLots               = 0.10;   // Fixed lot size
input int    InpStopLossPoints     = 10;     // Stop Loss in points
input int    InpTakeProfitPoints   = 40;     // Take Profit in points
input double InpBuyLevel           = 100.0;  // Buy level price
input double InpSellLevel          = 140.0;  // Sell/close level price
input int    InpDeviationPoints    = 20;     // Deviation in points
input ulong  InpMagicNumber        = 689862; // Magic number

input int    InpStartYear          = 2026;   // Backtest start year
input int    InpStartMonth         = 1;      // Backtest start month
input int    InpStartDay           = 1;      // Backtest start day
input int    InpEndYear            = 2026;   // Backtest end year
input int    InpEndMonth           = 3;      // Backtest end month
input int    InpEndDay             = 31;     // Backtest end day

CTrade trade;

datetime g_start_time = 0;
datetime g_end_time   = 0;

//+------------------------------------------------------------------+
//| Initialize date range                                            |
//+------------------------------------------------------------------+
datetime MakeTime(int year, int month, int day)
{
   MqlDateTime dt;
   ZeroMemory(dt);
   dt.year = year;
   dt.mon  = month;
   dt.day  = day;
   dt.hour = 0;
   dt.min  = 0;
   dt.sec  = 0;
   return StructToTime(dt);
}

//+------------------------------------------------------------------+
//| Check if current time is within the backtest window              |
//+------------------------------------------------------------------+
bool IsWithinTradeWindow(datetime t)
{
   return (t >= g_start_time && t <= g_end_time);
}

//+------------------------------------------------------------------+
//| Find current position for this symbol and magic                  |
//+------------------------------------------------------------------+
bool GetMyPosition(ulong &ticket, ENUM_POSITION_TYPE &type, double &volume, double &open_price)
{
   ticket = 0;
   type = (ENUM_POSITION_TYPE)-1;
   volume = 0.0;
   open_price = 0.0;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong pos_ticket = PositionGetTicket(i);
      if(pos_ticket == 0)
         continue;

      if(!PositionSelectByTicket(pos_ticket))
         continue;

      string sym = PositionGetString(POSITION_SYMBOL);
      long magic = (long)PositionGetInteger(POSITION_MAGIC);

      if(sym == _Symbol && (ulong)magic == InpMagicNumber)
      {
         ticket = pos_ticket;
         type = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         volume = PositionGetDouble(POSITION_VOLUME);
         open_price = PositionGetDouble(POSITION_PRICE_OPEN);
         return true;
      }
   }
   return false;
}

//+------------------------------------------------------------------+
//| Open buy position                                                |
//+------------------------------------------------------------------+
bool OpenBuy()
{
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   if(ask <= 0.0)
      return false;

   double sl = NormalizeDouble(ask - InpStopLossPoints * _Point, _Digits);
   double tp = NormalizeDouble(ask + InpTakeProfitPoints * _Point, _Digits);

   trade.SetExpertMagicNumber((long)InpMagicNumber);
   trade.SetDeviationInPoints(InpDeviationPoints);

   return trade.Buy(InpLots, _Symbol, ask, sl, tp, "Buy at level");
}

//+------------------------------------------------------------------+
//| Close existing position                                          |
//+------------------------------------------------------------------+
bool ClosePositionByTicket(ulong ticket)
{
   if(ticket == 0)
      return false;

   trade.SetExpertMagicNumber((long)InpMagicNumber);
   return trade.PositionClose(ticket);
}

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   g_start_time = MakeTime(InpStartYear, InpStartMonth, InpStartDay);
   g_end_time   = MakeTime(InpEndYear, InpEndMonth, InpEndDay);

   if(g_end_time < g_start_time)
   {
      Print("Invalid date range.");
      return INIT_FAILED;
   }

   trade.SetExpertMagicNumber((long)InpMagicNumber);
   trade.SetDeviationInPoints(InpDeviationPoints);

   return INIT_SUCCEEDED;
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   datetime now = TimeCurrent();

   if(!IsWithinTradeWindow(now))
      return;

   ulong ticket;
   ENUM_POSITION_TYPE type;
   double volume, open_price;

   bool has_position = GetMyPosition(ticket, type, volume, open_price);

   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   if(bid <= 0.0 || ask <= 0.0)
      return;

   // If no position exists, buy when price reaches or goes below the buy level.
   if(!has_position)
   {
      if(ask <= InpBuyLevel)
      {
         OpenBuy();
      }
      return;
   }

   // If a buy position exists, close it when price reaches or exceeds the sell level.
   if(type == POSITION_TYPE_BUY)
   {
      if(bid >= InpSellLevel)
      {
         ClosePositionByTicket(ticket);
      }
   }
}